pipeline:
  name: text-embedder-pipeline
  modules:
  - name: text-embedder
    models:
    - name: multi-qa-MiniLM-L6-cos-v1
      params:
        quantize:
          type: bool
    - name: msmarco-distilbert-dot-v5
      params:
        quantize:
          type: bool
    - name: all-MiniLM-L12-v2
      params:
        quantize:
          type: bool
    - name: all-mpnet-base-v2
      params:
        quantize:
          type: bool
    - name: all-MiniLM-L6-v2
      params:
        quantize:
          type: bool
    defaults:
      model: multi-qa-MiniLM-L6-cos-v1
    input:
      type: json
      permitted_extensions:
      - .json
    output:
      type: npy
