pipeline:
  name: keyword-search-pipeline
  modules:
  - name: keyword-search
    models:
    - name: base
    defaults:
      model: base
    input:
      type: text
      permitted_extensions:
      - .txt
      - .pdf
      - .docx
      - .pptx
    output:
      type: db
