pipeline:
  name: my-text-search-pipeline
  modules:
  - name: parser
    models:
    - name: sentence
    - name: fixed
      params:
        chunk_size:
          type: int
          default: 10
        overlap_size:
          type: int
          default: 2
    defaults:
      model: sentence
    input:
      type: text
      permitted_extensions:
      - .txt
      - .pdf
      - .docx
      - .pptx
    output:
      type: json
  - name: text-embedder
    models:
    - name: multi-qa-MiniLM-L6-cos-v1
      params:
        quantize:
          type: bool
          default: true
    - name: msmarco-distilbert-dot-v5
      params:
        quantize:
          type: bool
          default: true
    - name: all-MiniLM-L12-v2
      params:
        quantize:
          type: bool
          default: true
    - name: all-mpnet-base-v2
      params:
        quantize:
          type: bool
          default: true
    - name: all-MiniLM-L6-v2
      params:
        quantize:
          type: bool
          default: true
    defaults:
      model: multi-qa-MiniLM-L6-cos-v1
      params:
        quantize: true
    input:
      type: json
      permitted_extensions:
      - .json
    output:
      type: npy
  - name: vector-search
    models:
    - name: faiss
    defaults:
      model: faiss
    input:
      type: npy
      permitted_extensions:
      - .npy
    output:
      type: faiss
